[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "printBuddies"
authors = [{name='Matt Manes'}]
description = "Handful of utilities to do printing tricks to the terminal."
version = "0.0.1"
requires-python = ">=3.7"
